### ISSUE TITLE
Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by SimonTheSiro** [hakan-krgn/hCore#25]
Hello there,

I use the plugin's scoreborad function and as soon as I restart my plugin via plugman all players are kicked out of the game with the reason
[05:38:21] [Server thread/INFO]: simon_the_siro lost connection: Internal Exception: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled

After a bit of trying around, an error occurred where I could read that the HCore API is responsible for this error.

Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:554) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:229) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:214) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:178) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.scheduler.BukkitRunnable.runTaskLater(BukkitRunnable.java:79) ~[patched_1.16.5.jar:git-Paper-794]
at com.hakan.core.scheduler.HScheduler.run(HScheduler.java:205) ~[?:?]
at com.hakan.core.scheduler.HScheduler.run(HScheduler.java:160) ~[?:?]
at com.hakan.core.scoreboard.HScoreboard.update(HScoreboard.java:244) ~[?:?]
at de.simon.system.api.NXScoreboard.setLineParser(NXScoreboard.java:71) ~[?:?]
at de.simon.system.utils.NXScoreboardManager.setScoreboard(NXScoreboardManager.java:94) ~[?:?]
... 23 more

If there is anything new, or it was a mistake on my part, please just write back.

- Siro

**Comment by SimonTheSiro** [comment]
Thanks for the answer!
I tried your suggestion and it worked.
I appreciate your help.
