### ISSUE TITLE
packet listener issue

### ISSUE THREAD

**Issue by hamza-cskn** [hakan-krgn/hCore#73]
packet listener throws error.

This server is running Paper version git-Paper-514 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: dd216c1)
Previous version: git-Paper-220 (MC: 1.19.2)

```
[00:01:58 WARN]: java.lang.NoSuchFieldException: connection
[00:01:58 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[00:01:58 WARN]: 	at MasterDuels-bukkit-23.4.0.jar//mc.obliviate.masterduels.lib.hcore.utils.ReflectionUtils.getField(ReflectionUtils.java:76)
[00:01:58 WARN]: 	at MasterDuels-bukkit-23.4.0.jar//mc.obliviate.masterduels.lib.hcore.packet.player.PacketPlayer_v1_19_R3.register(PacketPlayer_v1_19_R3.java:52)
[00:01:58 WARN]: 	at MasterDuels-bukkit-23.4.0.jar//mc.obliviate.masterduels.lib.hcore.packet.PacketHandler.register(PacketHandler.java:112)
[00:01:58 WARN]: 	at MasterDuels-bukkit-23.4.0.jar//mc.obliviate.masterduels.lib.hcore.packet.PacketHandler.lambda$initialize$0(PacketHandler.java:32)
[00:01:58 WARN]: 	at MasterDuels-bukkit-23.4.0.jar//mc.obliviate.masterduels.lib.hcore.listener.ListenerAdapter.execute(ListenerAdapter.java:195)
[00:01:58 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[00:01:58 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:01:58 WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:01:58 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:01:58 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:01:58 WARN]: 	at net.minecraft.server.players.PlayerList.a(PlayerList.java:330)
[00:01:58 WARN]: 	at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
[00:01:58 WARN]: 	at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
[00:01:58 WARN]: 	at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
[00:01:58 WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:592)
[00:01:58 WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
[00:01:58 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1576)
[00:01:58 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[00:01:58 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[00:01:58 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[00:01:58 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[00:01:58 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hakan-krgn** [comment]
Fixed > https://github.com/hakan-krgn/hCore/releases/tag/0.7.0.8
